/**
 * College Administration
 * College system administration
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Course { 
    Id?: string;
    CourseName?: string;
    Description?: string;
    Duration?: number;
    Status?: boolean;
    Image?:string;
}