/**
 * College Administration
 * College system administration
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Exam { 
    id?: string;
    subject?: string;
    facId?: string;
    groupId?: string;
    room?: number;
    teacherId?: string;
    testNum?: string;
    duration?: string;
    examDate?: Date;
    status?: boolean;
}