/**
 * College Administration
 * College system administration
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Group { 
    id?: string;
    groupNumber?: string;
    numberOfStudent?: number;
    academicYear?: number;
    semester?: number;
    courses?: Array<string>;
    facId?: string;
    status?: boolean;
}