/**
 * College Administration
 * College system administration
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressBook } from './addressBook';
import { StudExam } from './studExam';
import { User } from './user';

export interface Student { 
    Id?: string;
    First_name?: string;
    Last_name?: string;
    Email?: string;
    Phone?: string;
    Gender?: string;
    Birth_date?: string;
    ClassNum?: string;
    Address?: AddressBook;
    Status?: boolean;
    Group_Id?: string;
    PersonalUser?: User;
    Grades?: Array<StudExam>;
}
