/**
 * College Administration
 * College system administration
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressBook } from './addressBook';
import { StudExam } from './studExam';
import { User } from './user';

export interface Student { 
    id?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    phone?: string;
    gender?: string;
    birthDate?: Date;
    classNum?: string;
    address?: Array<AddressBook>;
    status?: boolean;
    groupId?: string;
    personalUser?: User;
    grades?: Array<StudExam>;
}
